-- DROP TABLE IF EXISTS authors;
--
-- CREATE TABLE crypt
-- (
--     id          INT AUTO_INCREMENT PRIMARY KEY,
--     name        VARCHAR(250) NOT NULL,
--     date        VARCHAR(250) NOT NULL,
--     currencyUSD INT          NOT NULL,
--     currencyEUR INT          NOT NULL,
--     currencyRUB INT          NOT NULL,
-- );
--
--
--
-- INSERT INTO crypt(id, name, date, currencyUSD, currencyEUR, currencyRUB)
-- VALUES (1, 'bitcoin', '21.07.01 23:25', 50, 55, 60);
-- INSERT INTO crypt(id, name, date, currencyUSD, currencyEUR, currencyRUB)
-- VALUES (2, 'ETC', '21.07.01 23:25', 55, 54, 70);